### ISSUE TITLE
What Votes

### ISSUE THREAD

**Issue by thrize** [Steem-FOSSbot/Steem-FOSSbot.github.io#1]
Analyse and show statistics for what your followers / following users vote on.

Could show activity from just last few days.

Suggested by [(at)eroche](https://steemit.com/@eroche)

**Comment by kharoof** [comment]
In order to see what interests your followers it would be useful to see what they vote on.  In the same way as what tags reads what they tag, what votes could scrape your followers recent voting data. 

What would be interesting to analyse

- The tags of the posts that your followers vote on
- When they vote (time of day)
- What percentage are their votes. Do you get a lot of small votes or some big ones?
- Who votes the most
- What distribution of SP are the voters
- ....

**Comment by thrize** [comment]
note, considering merging this into #2 (steem-analytics) to combine this with What Tags and possibly more stuff
